kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv
  namespace: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nginx-pv
    type: DirectoryOrCreate
  storageClassName: nginx-storage-class
